name: Publier sur PyPI

on:
  push:
    branches:
      - main

jobs:
  build-n-publish:
    name: Compilation et Publication
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write # Requis pour créer des tags et des releases

    steps:
    - name: Récupérer le code du dépôt
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Extraire la version du pyproject.toml
      id: get_version
      run: |
        # yq est préinstallé sur ubuntu-latest et sait lire le TOML nativement
        VERSION=$(yq eval '.project.version' pyproject.toml)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Créer le Tag Git et la Release GitHub
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const version = `v${process.env.VERSION}`;
          
          try {
            await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/${version}`
            });
            core.info(`Le tag ${version} existe déjà. Passage à l'étape suivante.`);
          } catch (error) {
            if (error.status === 404) {
              core.info(`Création de la release et du tag ${version}...`);
              await github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: version,
                name: version,
                body: `Release automatique de la version ${version}`,
                draft: false,
                prerelease: false
              });
            } else {
              throw error;
            }
          }

    - name: Installer les outils de build
      run: python -m pip install build --user

    - name: Compiler le package
      run: python -m build

    - name: Publier sur PyPI via Trusted Publishing
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ./dist/
        skip-existing: true
